[build.environment]
CORS_ENABLED=true
CORS_ORIGIN=true
DB_CLIENT="sqlite3"
DB_FILENAME="./data.db"
RATE_LIMITER_ENABLED=false
RATE_LIMITER_STORE=memory
RATE_LIMITER_POINTS=25
RATE_LIMITER_DURATION=1
CACHE_ENABLED=false
STORAGE_LOCATIONS="local"
STORAGE_LOCAL_DRIVER="local"
STORAGE_LOCAL_ROOT="./uploads"
KEY="f47a4fee-a91c-4374-8d06-8b18a442ddfe"
SECRET="cij7j0BM3RzXCuyLfzJDy6NF4UdFQK6R"
ACCESS_TOKEN_TTL="15m"
REFRESH_TOKEN_TTL="7d"
REFRESH_TOKEN_COOKIE_SECURE=false
REFRESH_TOKEN_COOKIE_SAME_SITE="lax"
REFRESH_TOKEN_COOKIE_NAME="directus_refresh_token"
CORS_ENABLED=true
CORS_ORIGIN=true
EXTENSIONS_PATH="./extensions"
